#!/bin/sh

# sample: swpackage -s yaketystats.psf -d /tmp/blah -x run_as_superuser=false 

cat <<EOF
vendor
	tag		TSS
end

product
	tag		YaketyStats
	revision	1.3.3.1
	title		Stats to the right power
	machine_type	*
	os_name		HP-UX
	os_release	*
	os_version	?
	directory	/

	fileset
		tag		base
		title		YaketyStats base
		revision	1.3.3.1
		preinstall      /exports/Bonnie&Clyde/pkgs/YaketyStats/packies/preinst
		postremove      /exports/Bonnie&Clyde/pkgs/YaketyStats/packies/postrm

		directory       /exports/Bonnie&Clyde/pkgs/YaketyStats/share=/usr/local/share/doc/yaketystats
		file README
		file copyright
        end

	fileset
		tag		bin
		title		YaketyStats bin
		revision	1.3.3.1
		prerequisite	YaketyStats.base,r>=1.0
                postinstall     /exports/Bonnie&Clyde/pkgs/YaketyStats/packies/postinst

                # TODO
		#file /usr
		#file /usr/local
		#file /usr/local/yaketystats
		directory       /exports/Bonnie&Clyde/pkgs/YaketyStats=/usr/local/yaketystats

EOF

cd '/exports/Bonnie&Clyde/pkgs/YaketyStats'
find bin etc lib libexec | grep -v [.]svn | xargs -i echo "                file " {}

cat <<EOF
	end
end

EOF

