#!/bin/sh

# postremove for stats
#
# - Delete crontab
# - Delete user and group
OUR_USER=stats
OUR_GROUP=stats
PATH=/bin:/usr/bin:$PATH
# Wipe out crontab so the running cron stops trying to run jobs as stats
crontab -r $OUR_USER

# kill all of the user processes
ps -u $OUR_USER | grep -v PID | awk '{print $1}' | xargs -i kill {}
sleep 2
ps -u $OUR_USER | grep -v PID | awk '{print $1}' | xargs -i kill {}

userdel $OUR_USER
groupdel $OUR_GROUP
