#!/bin/sh

# postremove for stats
#
# - Delete crontab
# - Delete user and group
OUR_USER=stats
OUR_GROUP=stats
PATH=/bin:/usr/bin:/usr/sbin:$PATH
# Wipe out crontab so the running cron stops trying to run jobs as stats
if [ "`uname`" = Linux ]
then
  crontab -r -u $OUR_USER
else
  crontab -r $OUR_USER
fi

# kill all of the user processes
ps -u $OUR_USER | grep -v PID | awk '{print $1}' | xargs -i kill {}
sleep 2
ps -u $OUR_USER | grep -v PID | awk '{print $1}' | xargs -i kill {}

userdel $OUR_USER
grep "^${OUR_USER}:" /etc/group > /dev/null
if [ $? = 0 ]
then
  TMPDIR=/etc groupdel $OUR_GROUP
fi
