#!/bin/sh

# pre-install script for stats
#
# Create stats user and group 

CHROOT=""
ROOTDIR=/
if [ "`uname`" = SunOS ]
  then
  if [ ! -z "${PKG_INSTALL_ROOT}" ]
    then
    ROOTDIR="${PKG_INSTALL_ROOT}/"
    CHROOT="/usr/sbin/chroot ${ROOTDIR}"
  fi
fi

OUR_GROUP=stats
OUR_GID=11994
OUR_USER=stats
OUR_UID=11994

if [ -f /etc/redhat-release ]
then
  DIR=/usr/local/%{name}
else
  DIR=/usr/local/yaketystats
fi

grep "^$OUR_GROUP:" $ROOTDIR/etc/group > /dev/null
if [ $? = 0 ]
  then
  echo "Group $OUR_GROUP exists so I refuse to add it."
else
  $CHROOT /usr/sbin/groupadd -g $OUR_GID $OUR_GROUP
  if [ $? != 0 ]
  then
    echo "Ugh!  I'm dying an ugly death!  groupadd had an error :("
    exit 41
  fi
fi

grep "^$OUR_USER:" $ROOTDIR/etc/passwd > /dev/null
if [ $? = 0 ]
  then
  echo "User $OUR_USER exists so I refuse to add it."
  status=$?
else
  $CHROOT /usr/sbin/useradd -m -d $DIR -u $OUR_UID -g $OUR_GID $OUR_USER
  status=$?
fi
if [ $status != 0 ]
then
  echo "Ugh!  I'm dying an ugly death!  useradd had an error ($status).  Perhaps $DIR already exists?"
  exit 42
fi

chmod 755 $DIR
if [ $? != 0 ]
then
  echo "chmod 755 failed"
  exit 43
fi
