#!/usr/bin/env perl

# Copyright (C) 2008 Board of Regents of the University System of Georgia

# This file is part of YaketyStats (see http://yaketystats.org/).
#
# YaketyStats is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 2.
#
# YaketyStats is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with YaketyStats.  If not, see <http://www.gnu.org/licenses/>.

$|=1;

use strict;
use warnings;
use Cwd 'realpath';
our $g_dir = __FILE__;
$g_dir =~ s/\/[^\/]+$//;
$g_dir = realpath("$g_dir/..");
require "$g_dir/lib/include";

my (@data, $line);

# These are the defaults.  They could be semi-overridden by specifying a
# different interval in the client config file, but the RRD file would still have
# space for updates every $interval as defined below.
my $rrd_type = "GAUGE";
my $rrd_interval;

our ($g_exit, $g_default_timeout, $g_host, $g_sep, $g_collector);
$main::g_host = get_hostname ();
$main::g_collector = 'load';
default_plugin_opts ();

# If we haven't loaded subs.pl, then we've been run from the command-line.  That
# means we're in test mode.  So load include, define $g_host, and print results.
if ( !@ARGV || (! defined ($ARGV[1]) && $ARGV[1] eq "calledfromcollect") ) {
  # TODO: There must be a better way to get this path!  I think the better
  # way is called "perl module" :)
  local $main::g_fileit_mode = "test";
  # Silence warning
  $main::g_fileit_mode = $main::g_fileit_mode;
  get_ignores ();
  $rrd_interval = 60;
  fileit ("You ran $g_collector manually; setting interval to $rrd_interval.");
  @data = doit ();
  foreach my $line (@data) {
    print "$line";
  }
  print "\n";
} else {
  if ( defined ($ARGV[0]) && $ARGV[0] =~ /^\d+$/ ) {
    $rrd_interval = $ARGV[0];
  } else {
    fileit ("Ack!  No interval for $g_collector.  Bailing.", "err");
    exit ();
  }
  get_ignores ();
  @data = doit ();
  if ( defined ($data[0]) ) {
    bivalve (@data);
  } else {
    fileit ("Warning:  No data for $g_collector");
  }
}

# Sample uptime output:
#   Linux:
# 15:32:14 up 16 days,  1:10,  3 users,  load average: 0.00, 0.00, 0.00
#   HP-UX:
#  1:36pm  up 4 days, 29 mins,  2 users,  load average: 0.00, 0.00, 0.01
#   Solaris:
#  1:37pm  up 3 day(s), 23:54,  17 users,  load average: 0.64, 0.73, 0.67
# These are all basically the same so use this logic:
# Remove everything through "average:\s*", then split on ",\s*"
sub doit {
  my ($status, @data, $line, $load1, $load5, $load15, @return, $time);

  $time = time ();

  ($load1, $load5, $load15) =
    parse_cmd ('uptime', $g_default_timeout, 0, '.*average:\s*', ',\s*',
               'Unknown HZ value', 0, (0, 1, 2));
  check_vars ($g_exit, $load1, "load1", $load5, "load5", $load15, "load15");
  if ( ! ignoreit ('load', '1-minute') ) {
    push (@return, "p=/$main::g_host/load/1-minute${g_sep}t=$rrd_type${g_sep}i=$rrd_interval${g_sep}ts=$time${g_sep}v=$load1\n");
  }
  if ( ! ignoreit ('load', '5-minute') ) {
    push (@return, "p=/$main::g_host/load/5-minute${g_sep}t=$rrd_type${g_sep}i=$rrd_interval${g_sep}ts=$time${g_sep}v=$load5\n");
  }
  if ( ! ignoreit ('load', '15-minute') ) {
    push (@return, "p=/$main::g_host/load/15-minute${g_sep}t=$rrd_type${g_sep}i=$rrd_interval${g_sep}ts=$time${g_sep}v=$load15\n");
  }
  return (@return);
}
