#!/bin/sh

# Simple-minded munin plugin wrapper.  It runs plugins out of $munindir and
# stuffs the output into YaketyStats.  Run it from cron like this to
# collect munin memory stats every 5 minutes:
#
# /usr/local/yaketystats/libexec/munin_wrap 300 memory
#
# or like this to collect memory and cpu stats:
# /usr/local/yaketystats/libexec/munin_wrap 300 memory cpu
#
# List as many plugin names as you like on the command line
#
# Make sure your cron interval and the first argument match :)

# Munin plugin output looks like this:
# inactive.value 410927104

munindir=/usr/share/munin/plugins
fqdn=`cat /var/yaketystats/fqdn`
tmp=`mktemp /tmp/munin_memory.XXXXXX`
now=`date +%s`
sep=''

if [ $# -lt 2 ]
then
  echo "need at least two args"
  exit 1
fi

do_one () {
  $munindir/$stat | sed 's/[.]value//'  | while read name value
  do
    echo "p=/${fqdn}/munin_$stat/${name}${sep}t=GAUGE${sep}i=${interval}${sep}ts=${now}${sep}v=${value}" >> $tmp
  done
}

interval=$1
shift
if [ "$1" = "all" ]
then
  list="$munindir/*"
else
  list="$*"
fi

for stat in $list
do
  do_one $stat
done

/usr/local/yaketystats/bin/bivalve munin jojo < $tmp

rm -f $tmp
