#!/usr/bin/perl

# Copyright (C) 2008 Board of Regents of the University System of Georgia

# This file is part of YaketyStats (see http://yaketystats.org/).
#
# YaketyStats is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 2.
#
# YaketyStats is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with YaketyStats.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;
use Cwd 'realpath';
our $g_dir = __FILE__;
$g_dir =~ s/\/[^\/]+$//;
$g_dir = realpath("$g_dir/..");
require "$g_dir/lib/include";

my (@data, $line);

# These are the defaults.  They could be semi-overridden by specifying a
# different interval in the client config file, but the RRD file would still have
# space for updates every $interval as defined below.
my $rrd_type = "GAUGE";
my $rrd_interval;

our ($g_exit, $g_default_timeout, $g_host, $g_sep, $g_collector, $g_debug);
$main::g_host = get_hostname ();
$main::g_collector = "snmp";

our %econfig;
our $snmp_community;

# If we haven't loaded subs.pl, then we've been run from the command-line.  That
# means we're in test mode.  So load include, define $g_host, and print results.
if (! defined (@ARGV) || (! defined ($ARGV[1]) && $ARGV[1] eq "calledfromcollect") ) {
  # TODO: There must be a better way to get this path!  I think the better
  # way is called "perl module" :)
  local $main::g_fileit_mode = "test";
  # Silence warning
  $main::g_fileit_mode = $main::g_fileit_mode;
  get_ignores ();
  $rrd_interval = 300;
  fileit ("You ran $g_collector manually; setting interval to $rrd_interval.");
  @data = doit ();
  foreach my $line (@data) {
    print "$line";
  }
  print "\n";
} else {
  if ( defined ($ARGV[0]) && $ARGV[0] =~ /^\d+$/ ) {
    $rrd_interval = $ARGV[0];
  } else {
    fileit ("Ack!  No interval for $g_collector.  Bailing.", "err");
    exit ();
  }
  get_ignores ();
  @data = doit ();
  bivalve (@data);
  if ( defined ($data[0]) ) {
    bivalve (@data);
  } else {
    fileit ("Warning:  No data for $g_collector");
  }
}

sub doit {
  my ($host, $oid, $cmd, $status, @data, @return, $path, $time);
  my (%stupid);

  get_eval_config ("$ENV{HOME}/etc/snmp.config");

  $time = time ();
  foreach $host (keys (%econfig)) {
    foreach $oid (keys (%{ $econfig{$host} })) {
      $path = $econfig{$host}{$oid}{path};
      if ( defined ($stupid{"${host}.${path}"}) ) {
	fileit ("Hey!  You already collected $path!  I refuse to do it again.");
      } else {
	$stupid{"${host}.${path}"} = 1;
	$cmd = "snmpget -v1 -c '$snmp_community' $host $oid";
	($status, @data) = run_prg ($cmd, $g_default_timeout);
	if ( $status != 0 ) {
	  fileit ("problem with $cmd.  Output was:  @data");
	} else {
	  # Sample output
	  #SNMPv2-SMI::enterprises.476.1.1.1.1.2.6.0 = INTEGER: 100
	  chomp ($data[0]);
	  $data[0] =~ s/.*=.*: *//;
	  push (@return,
		"p=/$host/snmp/$path${g_sep}t=$rrd_type${g_sep}i=$rrd_interval${g_sep}ts=$time${g_sep}v=$data[0]\n");
	}
      }
    }
  }
  return (@return);
}

sub dumpit {
  my (%hash) = @_;
  print "Dumping.\n";
  print Data::Dumper->Dump ( [\%hash], ['*hash'] );
}

1;
